# Generated by Django 4.2.3 on 2023-07-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disquera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitDisquera', models.CharField(max_length=25)),
                ('nombreDisquera', models.CharField(max_length=100)),
                ('telefonoDisquera', models.CharField(max_length=15)),
                ('direccionDisquera', models.CharField(max_length=100)),
                ('estadoDisquera', models.BooleanField(default=False)),
            ],
        ),
    ]
