# Generated by Django 4.2.3 on 2023-07-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disquera_JD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddisquerafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disquera_JD.disquera')),
            ],
        ),
    ]
